version: '3'
services:
    app:
        image: koda/docker-knowledge
        #build: .
        volumes:
            - ./volumes/knowledge:/root/.knowledge
        ports:
            - "8080:8080"
        restart: always
        depends_on:
            - "db"
    db:
        image: postgres:9
        env_file:
            - wiki.env
        volumes:
            - ./volumes/postgres/data:/var/lib/postgresql/data
        restart: always